### ISSUE TITLE
ctrl+q is occupied by default in the latest sublime text3

### ISSUE THREAD

**Issue by clms2** [khrizt/GotoLastEdit#9]
```
KeyError: 151
Traceback (most recent call last):
  File "E:\work\Sublime Text Build\sublime_plugin.py", line 478, in run_callback
    expr()
  File "E:\work\Sublime Text Build\sublime_plugin.py", line 585, in <lambda>
    run_callback('on_modified', callback, lambda: callback.on_modified(v))
  File "E:\work\Sublime Text Build\Data\Installed Packages\GoToLastEdit.sublime-package\GotoLastEdit.py", line 31, in on_modified
    if CE.prev_line[view.id()] == -1 or curr_line != CE.prev_line[view.id()]:
```
it doesnt work in the latest version of sublime text3 (3197)
and I set the user key binging : `{ "keys": ["ctrl+q"]},`, it works again, but there is an error in console:
```
Unable to parse binding {keys: [ctrl+q]}
```
can I bind the real command of gotoLastEdit?thx.

**Comment by khrizt** [comment]
It's working for me in version 3200, but I'm on Ubuntu, not windows. I'll try to set up a windows scenario to test it
